### ISSUE TITLE
Any way to define the reverse operation for a serializer?

### ISSUE THREAD

**Issue by cafreeman** [stavro/remodel#5]
Hi there!

This library looks great, and I think it might be just the thing I've been needing for my own Elixir app. I've got an issue where my front-end uses a different schema than the rest of the services on the backend, so a serializer like this would be perfect.

That said, I'm curious if there's a way to "deserialize" the data when it comes back from the UI? In other words, it looks like Remodel is defining a one-way transformation. Is it possible to map the data back the other way as well? Like a `from_map` and `from_list` that does the reverse of `to_map` and `to_list`?

**Comment by stavro** [comment]
No - these are one-way transformations.  In theory, you could create a second counter-transformation that maps it one-way in the reverse, if the logic is complex enough to warrant it

**Comment by cafreeman** [comment]
Ah, good idea! Thanks :)
